
package web.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelWebServiceImplService", targetNamespace = "http://service.web/", wsdlLocation = "http://localhost:8080/Hilton.web-service?wsdl")
public class HotelWebServiceImplService
    extends Service
{

    private final static URL HOTELWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HOTELWEBSERVICEIMPLSERVICE_QNAME = new QName("http://service.web/", "HotelWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Hilton.web-service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HOTELWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HotelWebServiceImplService() {
        super(__getWsdlLocation(), HOTELWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HotelWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HotelWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HOTELWEBSERVICEIMPLSERVICE_QNAME);
    }

    public HotelWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public HotelWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HotelWebService
     */
    @WebEndpoint(name = "HotelWebServiceImplPort")
    public HotelWebService getHotelWebServiceImplPort() {
        return super.getPort(new QName("http://service.web/", "HotelWebServiceImplPort"), HotelWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelWebService
     */
    @WebEndpoint(name = "HotelWebServiceImplPort")
    public HotelWebService getHotelWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web/", "HotelWebServiceImplPort"), HotelWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HOTELWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HOTELWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
